<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository {

	function getArticles($category, $keywords) {

		$qb = $this->createQueryBuilder('a');

        if($category !== 'all') {

            $qb
                ->where('a.category = :category')
                ->setParameter('category', $category)
            ;
        }

        if($keywords !== '') {

        	$qb
                ->where('a.keywords LIKE :keywords')
                ->setParameter('keywords', '%'.$keywords.'%')
            ;
        }

        $articles = $qb->getQuery()->getResult();

        return $articles;
	}
}
